namespace BankStatementAnalyzer.Repository.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class RemovedCompanyIdFromBaseModel : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.AppMessage", "CompanyId", "dbo.Company");
            DropForeignKey("dbo.City", "CompanyId", "dbo.Company");
            DropForeignKey("dbo.AreaManager", "CompanyId", "dbo.Company");
            DropForeignKey("dbo.Category", "CompanyId", "dbo.Company");
            DropForeignKey("dbo.Complaint", "CompanyId", "dbo.Company");
            DropForeignKey("dbo.Coupon", "CompanyId", "dbo.Company");
            DropForeignKey("dbo.DeliveryBoy", "CompanyId", "dbo.Company");
            DropForeignKey("dbo.Email", "CompanyId", "dbo.Company");
            DropForeignKey("dbo.Gallery", "CompanyId", "dbo.Company");
            DropForeignKey("dbo.ImageCategory", "CompanyId", "dbo.Company");
            DropForeignKey("dbo.OrderDelvieryBoyMapping", "CompanyId", "dbo.Company");
            DropForeignKey("dbo.Address", "CompanyId", "dbo.Company");
            DropForeignKey("dbo.Order", "CompanyId", "dbo.Company");
            DropForeignKey("dbo.Payment", "CompanyId", "dbo.Company");
            DropForeignKey("dbo.PageManager", "CompanyId", "dbo.Company");
            DropForeignKey("dbo.Product", "CompanyId", "dbo.Company");
            DropForeignKey("dbo.SubCategory", "CompanyId", "dbo.Company");
            DropForeignKey("dbo.UnitOfMeasure", "CompanyId", "dbo.Company");
            DropForeignKey("dbo.PushNotification", "CompanyId", "dbo.Company");
            DropForeignKey("dbo.ReturnRequestDeliveryBoyMapping", "CompanyId", "dbo.Company");
            DropForeignKey("dbo.ReturnRequest", "CompanyId", "dbo.Company");
            DropForeignKey("dbo.Store", "CompanyId", "dbo.Company");
            DropForeignKey("dbo.Street", "CompanyId", "dbo.Company");
            DropForeignKey("dbo.StyleClass", "CompanyId", "dbo.Company");
            DropForeignKey("dbo.StyleTrait", "CompanyId", "dbo.Company");
            DropForeignKey("dbo.StyleTraitValue", "CompanyId", "dbo.Company");
            DropForeignKey("dbo.SupportAndFAQ", "CompanyId", "dbo.Company");
            DropForeignKey("dbo.TimeSlot", "CompanyId", "dbo.Company");
            DropForeignKey("dbo.UndeliveryReason", "CompanyId", "dbo.Company");
            DropForeignKey("dbo.Wallet", "CompanyId", "dbo.Company");
            DropIndex("dbo.AppMessage", new[] { "CompanyId" });
            DropIndex("dbo.AreaManager", new[] { "CompanyId" });
            DropIndex("dbo.City", new[] { "CompanyId" });
            DropIndex("dbo.Category", new[] { "CompanyId" });
            DropIndex("dbo.Complaint", new[] { "CompanyId" });
            DropIndex("dbo.Coupon", new[] { "CompanyId" });
            DropIndex("dbo.DeliveryBoy", new[] { "CompanyId" });
            DropIndex("dbo.Email", new[] { "CompanyId" });
            DropIndex("dbo.Gallery", new[] { "CompanyId" });
            DropIndex("dbo.ImageCategory", new[] { "CompanyId" });
            DropIndex("dbo.OrderDelvieryBoyMapping", new[] { "CompanyId" });
            DropIndex("dbo.Order", new[] { "CompanyId" });
            DropIndex("dbo.Address", new[] { "CompanyId" });
            DropIndex("dbo.Payment", new[] { "CompanyId" });
            DropIndex("dbo.PageManager", new[] { "CompanyId" });
            DropIndex("dbo.Product", new[] { "CompanyId" });
            DropIndex("dbo.SubCategory", new[] { "CompanyId" });
            DropIndex("dbo.UnitOfMeasure", new[] { "CompanyId" });
            DropIndex("dbo.PushNotification", new[] { "CompanyId" });
            DropIndex("dbo.ReturnRequestDeliveryBoyMapping", new[] { "CompanyId" });
            DropIndex("dbo.ReturnRequest", new[] { "CompanyId" });
            DropIndex("dbo.Store", new[] { "CompanyId" });
            DropIndex("dbo.Street", new[] { "CompanyId" });
            DropIndex("dbo.StyleClass", new[] { "CompanyId" });
            DropIndex("dbo.StyleTrait", new[] { "CompanyId" });
            DropIndex("dbo.StyleTraitValue", new[] { "CompanyId" });
            DropIndex("dbo.SupportAndFAQ", new[] { "CompanyId" });
            DropIndex("dbo.TimeSlot", new[] { "CompanyId" });
            DropIndex("dbo.UndeliveryReason", new[] { "CompanyId" });
            DropIndex("dbo.Wallet", new[] { "CompanyId" });
            DropColumn("dbo.AppMessage", "CompanyId");
            DropColumn("dbo.AreaManager", "CompanyId");
            DropColumn("dbo.City", "CompanyId");
            DropColumn("dbo.Category", "CompanyId");
            DropColumn("dbo.Complaint", "CompanyId");
            DropColumn("dbo.Coupon", "CompanyId");
            DropColumn("dbo.DeliveryBoy", "CompanyId");
            DropColumn("dbo.Email", "CompanyId");
            DropColumn("dbo.Gallery", "CompanyId");
            DropColumn("dbo.ImageCategory", "CompanyId");
            DropColumn("dbo.OrderDelvieryBoyMapping", "CompanyId");
            DropColumn("dbo.Order", "CompanyId");
            DropColumn("dbo.Address", "CompanyId");
            DropColumn("dbo.Payment", "CompanyId");
            DropColumn("dbo.PageManager", "CompanyId");
            DropColumn("dbo.Product", "CompanyId");
            DropColumn("dbo.SubCategory", "CompanyId");
            DropColumn("dbo.UnitOfMeasure", "CompanyId");
            DropColumn("dbo.PushNotification", "CompanyId");
            DropColumn("dbo.ReturnRequestDeliveryBoyMapping", "CompanyId");
            DropColumn("dbo.ReturnRequest", "CompanyId");
            DropColumn("dbo.Store", "CompanyId");
            DropColumn("dbo.Street", "CompanyId");
            DropColumn("dbo.StyleClass", "CompanyId");
            DropColumn("dbo.StyleTrait", "CompanyId");
            DropColumn("dbo.StyleTraitValue", "CompanyId");
            DropColumn("dbo.SupportAndFAQ", "CompanyId");
            DropColumn("dbo.TimeSlot", "CompanyId");
            DropColumn("dbo.UndeliveryReason", "CompanyId");
            DropColumn("dbo.Wallet", "CompanyId");
        }
        
        public override void Down()
        {
            AddColumn("dbo.Wallet", "CompanyId", c => c.Int(nullable: false));
            AddColumn("dbo.UndeliveryReason", "CompanyId", c => c.Int(nullable: false));
            AddColumn("dbo.TimeSlot", "CompanyId", c => c.Int(nullable: false));
            AddColumn("dbo.SupportAndFAQ", "CompanyId", c => c.Int(nullable: false));
            AddColumn("dbo.StyleTraitValue", "CompanyId", c => c.Int(nullable: false));
            AddColumn("dbo.StyleTrait", "CompanyId", c => c.Int(nullable: false));
            AddColumn("dbo.StyleClass", "CompanyId", c => c.Int(nullable: false));
            AddColumn("dbo.Street", "CompanyId", c => c.Int(nullable: false));
            AddColumn("dbo.Store", "CompanyId", c => c.Int(nullable: false));
            AddColumn("dbo.ReturnRequest", "CompanyId", c => c.Int(nullable: false));
            AddColumn("dbo.ReturnRequestDeliveryBoyMapping", "CompanyId", c => c.Int(nullable: false));
            AddColumn("dbo.PushNotification", "CompanyId", c => c.Int(nullable: false));
            AddColumn("dbo.UnitOfMeasure", "CompanyId", c => c.Int(nullable: false));
            AddColumn("dbo.SubCategory", "CompanyId", c => c.Int(nullable: false));
            AddColumn("dbo.Product", "CompanyId", c => c.Int(nullable: false));
            AddColumn("dbo.PageManager", "CompanyId", c => c.Int(nullable: false));
            AddColumn("dbo.Payment", "CompanyId", c => c.Int(nullable: false));
            AddColumn("dbo.Address", "CompanyId", c => c.Int(nullable: false));
            AddColumn("dbo.Order", "CompanyId", c => c.Int(nullable: false));
            AddColumn("dbo.OrderDelvieryBoyMapping", "CompanyId", c => c.Int(nullable: false));
            AddColumn("dbo.ImageCategory", "CompanyId", c => c.Int(nullable: false));
            AddColumn("dbo.Gallery", "CompanyId", c => c.Int(nullable: false));
            AddColumn("dbo.Email", "CompanyId", c => c.Int(nullable: false));
            AddColumn("dbo.DeliveryBoy", "CompanyId", c => c.Int(nullable: false));
            AddColumn("dbo.Coupon", "CompanyId", c => c.Int(nullable: false));
            AddColumn("dbo.Complaint", "CompanyId", c => c.Int(nullable: false));
            AddColumn("dbo.Category", "CompanyId", c => c.Int(nullable: false));
            AddColumn("dbo.City", "CompanyId", c => c.Int(nullable: false));
            AddColumn("dbo.AreaManager", "CompanyId", c => c.Int(nullable: false));
            AddColumn("dbo.AppMessage", "CompanyId", c => c.Int(nullable: false));
            CreateIndex("dbo.Wallet", "CompanyId");
            CreateIndex("dbo.UndeliveryReason", "CompanyId");
            CreateIndex("dbo.TimeSlot", "CompanyId");
            CreateIndex("dbo.SupportAndFAQ", "CompanyId");
            CreateIndex("dbo.StyleTraitValue", "CompanyId");
            CreateIndex("dbo.StyleTrait", "CompanyId");
            CreateIndex("dbo.StyleClass", "CompanyId");
            CreateIndex("dbo.Street", "CompanyId");
            CreateIndex("dbo.Store", "CompanyId");
            CreateIndex("dbo.ReturnRequest", "CompanyId");
            CreateIndex("dbo.ReturnRequestDeliveryBoyMapping", "CompanyId");
            CreateIndex("dbo.PushNotification", "CompanyId");
            CreateIndex("dbo.UnitOfMeasure", "CompanyId");
            CreateIndex("dbo.SubCategory", "CompanyId");
            CreateIndex("dbo.Product", "CompanyId");
            CreateIndex("dbo.PageManager", "CompanyId");
            CreateIndex("dbo.Payment", "CompanyId");
            CreateIndex("dbo.Address", "CompanyId");
            CreateIndex("dbo.Order", "CompanyId");
            CreateIndex("dbo.OrderDelvieryBoyMapping", "CompanyId");
            CreateIndex("dbo.ImageCategory", "CompanyId");
            CreateIndex("dbo.Gallery", "CompanyId");
            CreateIndex("dbo.Email", "CompanyId");
            CreateIndex("dbo.DeliveryBoy", "CompanyId");
            CreateIndex("dbo.Coupon", "CompanyId");
            CreateIndex("dbo.Complaint", "CompanyId");
            CreateIndex("dbo.Category", "CompanyId");
            CreateIndex("dbo.City", "CompanyId");
            CreateIndex("dbo.AreaManager", "CompanyId");
            CreateIndex("dbo.AppMessage", "CompanyId");
            AddForeignKey("dbo.Wallet", "CompanyId", "dbo.Company", "ID");
            AddForeignKey("dbo.UndeliveryReason", "CompanyId", "dbo.Company", "ID");
            AddForeignKey("dbo.TimeSlot", "CompanyId", "dbo.Company", "ID");
            AddForeignKey("dbo.SupportAndFAQ", "CompanyId", "dbo.Company", "ID");
            AddForeignKey("dbo.StyleTraitValue", "CompanyId", "dbo.Company", "ID");
            AddForeignKey("dbo.StyleTrait", "CompanyId", "dbo.Company", "ID");
            AddForeignKey("dbo.StyleClass", "CompanyId", "dbo.Company", "ID");
            AddForeignKey("dbo.Street", "CompanyId", "dbo.Company", "ID");
            AddForeignKey("dbo.Store", "CompanyId", "dbo.Company", "ID");
            AddForeignKey("dbo.ReturnRequest", "CompanyId", "dbo.Company", "ID");
            AddForeignKey("dbo.ReturnRequestDeliveryBoyMapping", "CompanyId", "dbo.Company", "ID");
            AddForeignKey("dbo.PushNotification", "CompanyId", "dbo.Company", "ID");
            AddForeignKey("dbo.UnitOfMeasure", "CompanyId", "dbo.Company", "ID");
            AddForeignKey("dbo.SubCategory", "CompanyId", "dbo.Company", "ID");
            AddForeignKey("dbo.Product", "CompanyId", "dbo.Company", "ID");
            AddForeignKey("dbo.PageManager", "CompanyId", "dbo.Company", "ID");
            AddForeignKey("dbo.Payment", "CompanyId", "dbo.Company", "ID");
            AddForeignKey("dbo.Order", "CompanyId", "dbo.Company", "ID");
            AddForeignKey("dbo.Address", "CompanyId", "dbo.Company", "ID");
            AddForeignKey("dbo.OrderDelvieryBoyMapping", "CompanyId", "dbo.Company", "ID");
            AddForeignKey("dbo.ImageCategory", "CompanyId", "dbo.Company", "ID");
            AddForeignKey("dbo.Gallery", "CompanyId", "dbo.Company", "ID");
            AddForeignKey("dbo.Email", "CompanyId", "dbo.Company", "ID");
            AddForeignKey("dbo.DeliveryBoy", "CompanyId", "dbo.Company", "ID");
            AddForeignKey("dbo.Coupon", "CompanyId", "dbo.Company", "ID");
            AddForeignKey("dbo.Complaint", "CompanyId", "dbo.Company", "ID");
            AddForeignKey("dbo.Category", "CompanyId", "dbo.Company", "ID");
            AddForeignKey("dbo.AreaManager", "CompanyId", "dbo.Company", "ID");
            AddForeignKey("dbo.City", "CompanyId", "dbo.Company", "ID");
            AddForeignKey("dbo.AppMessage", "CompanyId", "dbo.Company", "ID");
        }
    }
}
