// <auto-generated />
namespace BankStatementAnalyzer.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddedTables_Banners_BannerImages_CustomerLikes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedTables_Banners_BannerImages_CustomerLikes));
        
        string IMigrationMetadata.Id
        {
            get { return "202103250926387_AddedTables_Banners_BannerImages_CustomerLikes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
